# Generated by Django 5.2.15 on 2026-06-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('contenido', models.TextField(blank=True, verbose_name='contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos/', verbose_name='imagen')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de publicación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'artículo',
                'verbose_name_plural': 'artículos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
